version: '3'
services:
    app: 
        container_name: docker-node-postgres
        restart: always
        build: .
        volumes: 
            - .:/usr/app/
            - /usr/app/node_modules
        ports: 
            - '80:3001'
        links:
            - postgres
    postgres:
        container_name: postgres
        image: postgres:11.3 
        ports: 
            - '8080:8080'
